### ISSUE TITLE
Syncing a GitHub Repo with its own actions automatically gets triggered

### ISSUE THREAD

**Issue by zibdie** [repo-sync/github-sync#105]
I have a repository that syncs another GitHub repository.

The issue is that this repository has its own GitHub actions. When `github-sync` runs, it also triggers that external repository too.
I would like to remove all files under the `.github` folder on the repository being synced before uploading to mine.

Is that possible?

**Comment by wei** [comment]
Unfortunately it is currently not possible to remove files during sync. You could look into writing custom github actions workflows that may suit your needs.
