### ISSUE TITLE
Off-topic: Deletion of git-sync

### ISSUE THREAD

**Issue by Galdanwing** [repo-sync/github-sync#110]
Hello.

Sorry for an issue that's not 100% related to this project, but I see that this repo mentions git-sync and, Wei He is part of the contributors here. 

The git-sync ([https://github.com/marketplace/actions/git-sync-action](url) repo got deleted very recently. Do you perhaps know why? I was using it for some projects, and now I need to sync them manually again, and was hoping to figure out what is going on.

To keep it somewhat on track I can create a pull-request removing the documention mentioning git-sync

**Comment by rmgpanw** [comment]
Same issue here. Many thanks in advance

**Comment by IlyaBelykh** [comment]
@wei profile is also unavailable. It is pretty disappointinge because I was using his version of repo-sync since it gives you the ability to set the destination repo explicitly. Does anyone have the sources of his version of this action left?

**Comment by morganschoen** [comment]
Also experiencing this issue. The one @IlyaBelykh mentions may be the same.

Another alternative is to construct your own copy from Google cache as the original was only 5 files.

Original repo: https://webcache.googleusercontent.com/search?q=cache:qhdzlH5dNisJ:https://github.com/wei/git-sync&cd=2&hl=en&ct=clnk&gl=ca

Files:

https://webcache.googleusercontent.com/search?q=cache:yPCWX0Jb_x4J:https://github.com/wei/git-sync/blob/master/README.md&cd=2&hl=en&ct=clnk&gl=ca

https://webcache.googleusercontent.com/search?q=cache:zt4N5zaWPTQJ:https://github.com/wei/git-sync/blob/master/entrypoint.sh&cd=2&hl=en&ct=clnk&gl=ca

https://webcache.googleusercontent.com/search?q=cache:jaCgAM18E60J:https://github.com/wei/git-sync/blob/master/git-sync.sh&cd=2&hl=en&ct=clnk&gl=ca

https://webcache.googleusercontent.com/search?q=cache:jxXX94SgjcoJ:https://github.com/wei/git-sync/blob/master/Dockerfile&cd=2&hl=en&ct=clnk&gl=ca

https://webcache.googleusercontent.com/search?q=cache:gcSx5LR3f4cJ:https://github.com/wei/git-sync/blob/master/action.yml&cd=2&hl=en&ct=clnk&gl=ca

**Comment by morganschoen** [comment]
FYI, the original repo appears to be working again.

**Comment by wei** [comment]
It's back, sorry for the inconvenience.
