### ISSUE TITLE
Support syncing specific tags

### ISSUE THREAD

**Issue by Goooler** [repo-sync/github-sync#119]
Now we can just sync all tags with `sync_tags: true`, it would be great to add a new option to sync specific tags like `sync_tags: "android-14.0.0_*"` to match the tags from https://android.googlesource.com/platform/packages/apps/Launcher3.

**Comment by heiskr** [comment]
Hello,

That functionality isn't supported with this workflow, you'll need to build a separate script or action to do that.

**Comment by Goooler** [comment]
I addressed the fix to #121.
