### ISSUE TITLE
feature/docker-hub

### ISSUE THREAD

**Issue by guiadco** [repo-sync/github-sync#13]
**Describe**
Is that possible to have a image on the docker hub ?

**Reason**
You can gain time using docker image instead of using action, because action need to build the container before starting the action.

**Comment by wei** [comment]
Thanks for the suggestion.

GitHub just released GitHub Container Registry which allows anonymous access. We'll definitely add it soon!

**Comment by wei** [comment]
Done. No changes are needed if you're on `@v2`. You'll automatically get the benefit of the faster action speed.

https://github.com/repo-sync/github-sync/blob/7c0db2f264834c5a01812e62c7e3f15c49634981/action.yml#L20-L22
