### ISSUE TITLE
Only syncing specific folders

### ISSUE THREAD

**Issue by Andre601** [repo-sync/github-sync#14]
I was wondering if this action can be used to only sync specific folders/directories.

I have a bot which supports multiple languages and allows people to submit their translations.
Those translations are on a separate repository (which I just call "source" in this example), but I also have those files in the repo of my bot (Calling it "target") and want those to be up to date, so this action could be useful.
The issue here would be two major things:
1. I don't want to sync everything from the source repo. For example, would I want to leave away the README and the `.github` folder from sync and only transfer the content of the `lang` folder.
2. The direction of the `lang` folder in the target repo isn't the same as the source repo (See below)

Folder structure:
```
Source          Target
  |               |
  |               |- src
  |                   |
  |                   |- main
  |                       |
  |                       |- resources
  |                           |
  |- lang                     |- lang
      |                           |
      |- de.json                  |- de.json
      |- en.json                  |- en.json
      |- ko.json                  |- ko.json
```

As you can see is the location of the lang folder in the Target repo completely different from the one in the source repo.
So would it be possible to define a relative path to get the files from/push the files to?

**Comment by wei** [comment]
Thanks for the detailed ticket. Have you looked at git submodules? Sounds like the model use-case for it.

**Comment by Andre601** [comment]
Yes I looked at it and from what I understand would this only link information (Kind of making a link-connection to the repo) and not sync content itself, which is not what I'm looking for.

**Comment by wei** [comment]
The content will be cloned when performing `git clone --recursive` it will allow management of lang in a separate repo without worrying about committing files back to the original repo. 

You can still write your own github action to do what you want but it's out of the scope for this project at this time.

**Comment by Andre601** [comment]
Kinda funny you mention this now...
I'm not good as coding stuff in languages other than Java, but I took some inspiration of [Decathlon/wiki-page-creator-action](https://github.com/Decathlon/wiki-page-creator-action) to make my own [entrypoint.sh](https://github.com/Andre601/repository-sync/blob/master/entrypoint.sh)

But since I'm not an expert on this, do I not know if I make stuff right or wrong, so if you have any feedback would I highly appreciate it.

**Comment by wei** [comment]
I cannot say right or wrong from just looking at the file but It seems you are on the right track. Just test with multiple repos extensively to make sure everything is working and make tweaks as needed.
