### ISSUE TITLE
Action file is overridden

### ISSUE THREAD

**Issue by flynfish** [repo-sync/github-sync#16]
How do you prevent the action file from being overwritten when the master branch is synced from the remote repo?

I tried putting the repo-sync.yml in a different branch but it doesn't seem that github runs workflows from branches other than master?

**Comment by flynfish** [comment]
In order to solve for this I had to put the action file in a different branch and make that branch the default branch.

**Comment by wei** [comment]
Yes, GitHub only uses workflows in the default branch. Thanks for sharing your use case and solution.
