### ISSUE TITLE
Sync removing .github/workflow

### ISSUE THREAD

**Issue by douglaskastle** [repo-sync/github-sync#19]
Hi there

Maybe I am missing something.  I want to mirror a git repo that is on the internet, but not on github.  I try and use your script/yml.  And it works great the first time.  However since the .github and recursive directories are not present on the remote repo the directory gets removed and then the mirroring stops.

Am I missing something, How do I mirror a repo I don't have write access into?

**Comment by wei** [comment]
GitHub only executes Actions on the default branch so your observation is correct, once actions yml is removed, the action is gone. 

Two ideas:
# Create a new branch with the actions file and make it the default branch. Pro: Easy, Con: the default view on GitHub will no longer be `master`, but `master` works just fine locally
# Modify our action. Fork this action and add a `destination_repo` input to handle it. That way, you can have a separate repository that contains all actions you'd like to run.

Please reply if you have any questions : D

**Comment by douglaskastle** [comment]
I was consider the number 2 option, I have a number or repos i want to mirror, so I could set up a special repo for that.

Looking at your work, what is the best way to contact if there are any questions?

**Comment by wei** [comment]
You can email me or chat with me on the website on my profile. PR welcome!

**Comment by douglaskastle** [comment]
I tried some of that.  There appears to be an issue if trying to push from the actions of one repo into another, even if the credentials are correct:

https://github.community/t5/GitHub-Actions/Automating-push-to-public-repo/m-p/52156#M8421

Here is the fork of your work with the destination repo and passing in the user password as a secret (either the secret of the GITHUB_TOKEN is not working in this case)

https://github.com/nangtani/github-sync

**Comment by lnxpy** [comment]
@wei The first solution was kinda smooth. Thanks. :)
