### ISSUE TITLE
Ignore File

### ISSUE THREAD

**Issue by memcoreDE** [repo-sync/github-sync#20]
It is possible the ignore some File? 
Like gitignore.

I like to sync repro´s excluding "Dockerfile", because i will use my own Dockerfile for some Repro´s.

**Comment by wei** [comment]
You'll want to use something like wei/pull with advanced configurations to merge in changes anytime there's an update.

**Comment by memcoreDE** [comment]
> 
> 
> You'll want to use something like wei/pull with advanced configurations to merge in changes anytime there's an update.

Thanks. I will test it.
