### ISSUE TITLE
Would you have plan to support syncing all tags?

### ISSUE THREAD

**Issue by niku** [repo-sync/github-sync#24]
My forked repository was synced all branches with using [Advanced Usage: Sync all branches](https://github.com/repo-sync/github-sync/tree/bda99324450c6c9cebcb15c5566126fb55131041#advanced-usage-sync-all-branches).
However, it doesn't seem syncing tags.

Would you have plan to support syncing all tags?

By the way, thank you for providing such a nice github action 👍

**Comment by wei** [comment]
Please try my other action [wei/git-sync](https://github.com/wei/git-sync) for this use case. Thank you!

**Comment by wei** [comment]
Please try my other action [wei/git-sync](https://github.com/wei/git-sync) for this use case. Thank you!
