### ISSUE TITLE
Something I noticed and a question to choose various merge options

### ISSUE THREAD

**Issue by em108** [repo-sync/github-sync#26]
Hello and thank you so much for the repo-sync. I wanted to point out something I noticed as though the app works absolutely fine, there was a situation when the force push would erase all the previous changes done in a private repository while syncing from the public repository. It would further erase the `repo-sync.yml` created in the private repo in the process and thus further jobs wouldn't be able to be done until you create it again in the workflows file.

I further wanted to as whether it would be possible to customize such that the repo-sync would have the option to create a pull request and choose from different merge options like 'merge' for example thereby keeping the changes.
This is what I am trying to imply; `pull changes from the source repo and push to your repository with a merge rather than force.` Much as rather what is offered in the `pull app.`

Thank you so much for the wonderful development!

**Comment by wei** [comment]
Thanks @em108 for trying out repo-sync and pull app! 

With the introduction to manual trigger [`workflow_dispatch`](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/), [I haven't tried it, but it looks like,] you should be able to create a new branch containing only the workflow then trigger it manually or create something that triggers it on a schedule.

For the second question, you can take a look at [repo-sync/repo-sync](https://github.com/repo-sync/repo-sync) and configure something similar. Basically breaking up your use case into 3 workflow actions.
1. use `repo-sync/github-sync` to fetch public repo's `master` to private repo's `upstream` branch.
1. use `repo-sync/pull-request` to create a pull request from `upstream` to `master` in private repo.
1. merge the pull request after it's created.

Please reply if you have any luck with using `workflow_dispatch` or have any other questions. Thanks!!
