### ISSUE TITLE
Project description missing word "action"

### ISSUE THREAD

**Issue by alex-page** [repo-sync/github-sync#6]
The project description says:
"A GitHub for syncing current repository with remote"

It should say:
"A GitHub action for syncing current repository with remote"

**Comment by zeke** [comment]
Fixed! Thanks for reporting. ⭐️ 

<img width="497" alt="Screen Shot 2019-09-13 at 3 36 15 PM" src="https://user-images.githubusercontent.com/2289/64898513-3fe70f80-d63c-11e9-9661-25215732c20f.png">

**Comment by zeke** [comment]
@all-contributors please add @alex-page for bugs
