### ISSUE TITLE
Autofetch all forks

### ISSUE THREAD

**Issue by MartinX3** [repo-sync/github-sync#9]
Dear developers,

thank you for your nice tool.

Since I can use the `*` to sync all branches without naming them, is it possible to use `*` to automatically iterate through all forks of my organization?

Manually adding all of them and don't forgetting it after forking a new repo is a bit meehhh, especially on higher fork counts.

**Comment by wei** [comment]
Thanks for using the action and filling the issue! 

Pushing a-repo/*:b-repo/* is actually a command supported by git push. Afaik there is no simple git command for your use case, but You can write a script to automatically create a branch and add the workflow file and run that on every repo you fork. It can be a simple greasemonkey script on the browser, a python/node script, or if you want to be fancy, a GitHub app that listens to installation_repositories.added event to perform the steps above. 😃
