### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by Cdimock** [repo-sync/github-sync#94]
Hello! We're getting this error in the last week when using this action.

I believe this is related to a recent [git vulnerability upgrade](https://github.blog/2022-04-12-git-security-vulnerability-announced/)

```
Run repo-sync/github-sync@v2.0.0
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Comment by heiskr** [comment]
Thank you for opening this issue. I believe Actions runners have been updated to avoid this issue, but let us know if the issue persists.
